### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by jb-angus** [DynamoMTL/shopify-pipeline#112]
I've been trying to get started with this but having issues getting it installed. When I run this in Windows cmd

`yarn create shopify-pipeline name-of-your-project`

I get this error.
```
Installing shopify-pipeline. This could take a while.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarnpkg ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error Command failed.
Exit code: 1
```

Has anyone experienced this or know what the issue may be?

**Comment by alexleclair** [comment]
What version of node are you using? What version of yarn?

**Comment by jb-angus** [comment]
Thanks for the reply. I'm using
Node: v8.9.4
Yarn: 1.3.2

I can confirm it's a Windows specific issue. I have been able to build successfully on Mac.

**Comment by alexleclair** [comment]
I'd definitely try with a different version of node (do you have NVM?).
Might be totally unrelated, but I had a similar issue on Slate a while back. Reverting to node `v6.12.1 LTS` fixed the issue.
